name: Docker publish

on:
  release:
    types: [published]

jobs:

  build_docker_image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Get model name from tag
      id: model
      run: echo "MODEL=${GITHUB_REF/refs\/tags\/v/}" >> "$GITHUB_OUTPUT"
    - name: Replace model name in start.sh script
      run: echo "MODEL=$(echo ${GITHUB_REF#refs/tags/v} | sed 's/:/\//g')" >> "$GITHUB_OUTPUT"
    - name: Docker Login
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build & push ollama
      uses: docker/build-push-action@v6
      with:
        context: .
        file: Dockerfile
        push: true
        tags: |
          ghcr.io/scai-bio/ollama-docker/${{ steps.model.outputs.MODEL }}